# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip', models.CharField(max_length=64, verbose_name='ip地址')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('Private_key', models.FileField(default=None, upload_to='key/')),
                ('Private_password', models.TextField(default=None, verbose_name='密钥密码')),
            ],
        ),
        migrations.CreateModel(
            name='log_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32, verbose_name='项目名称')),
                ('log_path', models.CharField(max_length=255, verbose_name='日志地址')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_log.host')),
            ],
        ),
    ]
