# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(default=None, max_length=255, verbose_name='密码'),
        ),
    ]
