# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-01 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='command_log.project_info'),
        ),
    ]
